apiVersion: v1
data:
  000-core.yaml: |
    admin:
      endpoint: localhost:8089
      insecure: true
    catalog-cache:
      endpoint: localhost:8081
      insecure: true
      type: datacatalog
    cluster_resources:
      standaloneDeployment: false
      templatePath: /etc/flyte/cluster-resource-templates
    logger:
      show-source: true
      level: 6
    propeller:
      create-flyteworkflow-crd: true
    webhook:
      certDir: /var/run/flyte/certs
      localCert: true
      secretName: flyte-sandbox-webhook-secret
      serviceName: flyte-sandbox-webhook
      servicePort: 443
    flyte:
      admin:
        disableClusterResourceManager: false
        disableScheduler: false
        disabled: false
        seedProjects:
        - flytesnacks
      dataCatalog:
        disabled: false
      propeller:
        disableWebhook: false
        disabled: false
  001-plugins.yaml: |
    tasks:
      task-plugins:
        default-for-task-types:
          container: container
          container_array: k8s-array
          sidecar: sidecar
        enabled-plugins:
        - container
        - sidecar
        - k8s-array
    plugins:
      logs:
        kubernetes-enabled: true
        kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
        cloudwatch-enabled: false
        stackdriver-enabled: false
      k8s:
        co-pilot:
          image: "cr.flyte.org/flyteorg/flytecopilot:v0.0.33"
      k8s-array:
        logs:
          config:
            kubernetes-enabled: true
            kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
            cloudwatch-enabled: false
            stackdriver-enabled: false
  002-database.yaml: |
    database:
      postgres:
        username: postgres
        host: flyte-sandbox-postgresql
        port: 5432
        dbname: flyte
        options: "sslmode=disable"
  003-storage.yaml: |
    propeller:
      rawoutput-prefix: s3://my-s3-bucket/data
    storage:
      type: stow
      stow:
        kind: s3
        config:
          region: us-east-1
          disable_ssl: true
          v2_signing: true
          endpoint: http://flyte-sandbox-minio.flyte:9000
          auth_type: accesskey
      container: my-s3-bucket
  100-inline-config.yaml: |
    plugins:
      k8s:
        default-env-vars:
        - FLYTE_AWS_ENDPOINT: http://flyte-sandbox-minio.flyte:9000
        - FLYTE_AWS_ACCESS_KEY_ID: minio
        - FLYTE_AWS_SECRET_ACCESS_KEY: miniostorage
    storage:
      signedURL:
        stowConfigOverride:
          endpoint: http://localhost:30002
  task_resources: |
    defaults:
      cpu: 1000m
      memory: 1000Mi
      storage: 1000Mi
    limits:
      cpu: 2
      gpu: 1
      memory: 7Gi
      storage: 2000Mi
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yT0WrcPBCFX8XMteWVs//+uyvoRWhTWtqmhYaWQiCM5dm1anlkJNmJCXn3Ym9sQknT3lk6M5/PnLHvAVvzjXwwjkFBn0MKJUYEdQ9SSqGdp2zAxoICLBvD6pqThLhsneGoEus02sqFqHZytx81w4F050kl0Xd0zRojWncUGnVFkIKUuWhtdzQcZnDEUIcJPD7N6nSRJCUdsLNRHJwXkxyHlmYxSbTjiIYn8JkYrRcYFsvzeSpvXYhHv/R2gTxjQ2oRTvfTNMnBDpFEwBN5LUJ0Ho8LuPWuJWvJTzCPt66LbRdF6+lg7lQS1mq1agYR1qLodE1xNVq55kfM2AUp5FIKw9YwCe34YI4L/kkE9e73KIh70aOfr0Xy9uOPq4ub8+9fby4u33z5/P7ySiXwkEJtuAQFryf2J2whhYYizgtGZhcxGsdhPLriJ+kYKGbeuExjjJYy41ZmZED6R93dMnlx7GtQUK/DE6XP0+SD4fLVeVk6/iti3AYomKL/p+LQoh476q4gEYYQqRnHtliQnUbCts1G0TNFCtMwHCKyXt4zrrgs3B2kzxQ3yHikUhQDKHhHtnm26qntF3H98p/lWf5/JiGFimyThWqlK/RxgRSG0Q+il1me5fKFKCoMFSiQ+32+3f2Xlxt5puX2sCk3m91hl+t8v89lsTvbbgqUWxrDec7t49cHJ3VO9bSHh4dfAQAA//9iPQ1CJAQAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: flyte
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-10-20T22:39:08Z"
  labels:
    app.kubernetes.io/instance: flyte-sandbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flyte-sandbox
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: flyte-binary-v0.1.10
    objectset.rio.cattle.io/hash: 09917841d502c07f5d558f81c19910b8275ba07e
  name: flyte-sandbox-config
  namespace: flyte
  resourceVersion: "48173"
  uid: 35a85873-c84d-493b-9946-783ac0e25b51
