apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-sandbox-config
data:
  task_resources: |
    defaults:
      cpu: 1000m
      memory: 1000Mi
      storage: 1000Mi
    limits:
      cpu: 2
      gpu: 1
      memory: 7Gi
      storage: 2000Mi
